#!/usr/bin/env bash
#
# One-time droplet setup. Run as root on a fresh Ubuntu 24.04 droplet.
#   ssh root@<droplet-ip>
#   bash <(curl -fsSL https://raw.githubusercontent.com/.../bootstrap.sh)
# (or scp this file up first and: bash bootstrap.sh)
#
# What it does:
#   - System updates + base packages
#   - Python 3.12 venv tooling
#   - PostgreSQL 16 with a dedicated `rcq` role and database
#   - Caddy (reverse proxy with auto Let's Encrypt SSL)
#   - UFW firewall (22/80/443 only — TURN ports added when coturn lands)
#   - Dedicated `rcq` system user owning /opt/rcq and /var/log/rcq
#   - Auto-generated DB password and JWT secret written to /opt/rcq/.env
#   - Nightly pg_dump kept locally for 7 days under /var/backups/rcq
#
# After this finishes:
#   - From your Mac: `bash deploy/deploy.sh <droplet-ip>` to push the backend code.
#   - The Caddyfile assumes the API lives at api.rcq.app — point that A-record
#     at the droplet IP BEFORE running, otherwise the cert request fails.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Run as root: sudo bash bootstrap.sh"
    exit 1
fi

echo "==> apt update + base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y \
    python3.12 python3.12-venv python3-pip \
    git curl rsync ufw ca-certificates \
    postgresql postgresql-contrib \
    debian-keyring debian-archive-keyring apt-transport-https gnupg

echo "==> Installing Caddy"
if ! command -v caddy >/dev/null 2>&1; then
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -y
    apt-get install -y caddy
fi

echo "==> Firewall (ufw)"
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
# coturn — TURN server for WebRTC NAT-traversal. UDP/TCP 3478 for the
# control channel, UDP 49152-65535 for the relay range.
ufw allow 3478/tcp
ufw allow 3478/udp
ufw allow 49152:65535/udp
ufw --force enable

echo "==> Installing coturn (TURN server)"
apt-get install -y coturn
TURN_SECRET=$(openssl rand -base64 32 | tr -d '/+=' | head -c 40)
PUBLIC_IP=$(curl -s https://api.ipify.org)
cat > /etc/turnserver.conf <<-EOTURN
# Generated by bootstrap.sh — TURN REST API auth via static-auth-secret.
listening-port=3478
listening-ip=0.0.0.0
external-ip=${PUBLIC_IP}
realm=rcq.app

use-auth-secret
static-auth-secret=${TURN_SECRET}

min-port=49152
max-port=65535

# Don't relay to private IPs — prevents abuse as an open proxy.
no-loopback-peers
no-multicast-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255

no-stdout-log
syslog
fingerprint
no-tlsv1
no-tlsv1_1
EOTURN
sed -i "s/^#TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/" /etc/default/coturn
grep -q "^TURNSERVER_ENABLED=1" /etc/default/coturn || echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn
systemctl enable --now coturn

echo "==> rcq system user"
if ! id -u rcq >/dev/null 2>&1; then
    useradd --system --create-home --home-dir /opt/rcq --shell /bin/bash rcq
fi
mkdir -p /opt/rcq /opt/rcq/app /opt/rcq/media /var/log/rcq /var/backups/rcq
chown -R rcq:rcq /opt/rcq /var/log/rcq /var/backups/rcq

echo "==> PostgreSQL role + database"
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='rcq'" | grep -q 1; then
    DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
    sudo -u postgres psql <<-EOSQL
        CREATE USER rcq WITH PASSWORD '${DB_PASSWORD}';
        CREATE DATABASE rcq OWNER rcq;
        GRANT ALL PRIVILEGES ON DATABASE rcq TO rcq;
EOSQL
    echo "${DB_PASSWORD}" > /opt/rcq/.db_password
    chmod 600 /opt/rcq/.db_password
    chown rcq:rcq /opt/rcq/.db_password
else
    echo "  (rcq role already exists, skipping create)"
    DB_PASSWORD=$(cat /opt/rcq/.db_password 2>/dev/null || echo "REUSE_EXISTING")
fi

echo "==> Application .env"
if [[ ! -f /opt/rcq/.env ]]; then
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
    cat > /opt/rcq/.env <<-EOENV
DATABASE_URL=postgresql+asyncpg://rcq:${DB_PASSWORD}@127.0.0.1:5432/rcq
JWT_SECRET=${JWT_SECRET}
ENV=prod
APP_NAME=RCQ
TURN_HOST=${PUBLIC_IP}
TURN_SECRET=${TURN_SECRET}
EOENV
    chmod 600 /opt/rcq/.env
    chown rcq:rcq /opt/rcq/.env
else
    echo "  (/opt/rcq/.env already exists, leaving alone)"
fi

echo "==> Python venv"
sudo -u rcq python3.12 -m venv /opt/rcq/venv

echo "==> Nightly pg_dump (cron at 03:30)"
cat > /etc/cron.d/rcq-backup <<-'EOCRON'
30 3 * * * postgres pg_dump rcq | gzip > /var/backups/rcq/rcq-$(date +\%Y\%m\%d).sql.gz && find /var/backups/rcq -name 'rcq-*.sql.gz' -mtime +7 -delete
EOCRON
chmod 644 /etc/cron.d/rcq-backup

echo ""
echo "==> Bootstrap complete."
echo ""
echo "Next steps (from your Mac):"
echo "  1. Make sure DNS A-record api.rcq.app → $(curl -s https://api.ipify.org)"
echo "  2. Run from project root: bash deploy/deploy.sh $(curl -s https://api.ipify.org)"
echo ""
echo "Saved credentials:"
echo "  /opt/rcq/.env          — DATABASE_URL, JWT_SECRET (do NOT commit)"
echo "  /opt/rcq/.db_password  — DB password only (kept for pg_dump scripts)"
